@Token = Bearer sk_live_7hrvb3jzvid42lnyv20vw7eqsucenawr

POST https://zingerad.zingerwallet.com/api/v1/generate-payment-link/
Content-Type: application/json
Authorization:  {{Token}}

{
  "ref_num": "ZIC2EFE2",
  "amount": 3000
}

###
POST https://zinger-ticket.herokuapp.com/api/ticket/create_ticket/hanis
Content-Type: application/json

{
    "user":{"email":"hanis@gmail.com"},
    "quantity":1,
    "ticket":{"type":"prime","price":100}
}

###
POST https://zinger-ticket.herokuapp.com/api/ticket1/update_ticket/
Content-Type: application/json

{
  "ref_num": "ZIC2EFE2",
  "amount": 3000,
  "reference":"ZI121",
  "status":"success"
}


###
GET https://zinger-ticket.herokuapp.com/api/user/loggedin



###
POST https://localhost:5000/api/ticket1/update_ticket/
Content-Type: application/json

{
  "ref_num": "ZIC2EFE2",
  "amount": 3000,
  "reference":"ZI121",
  "status":"success"
}